### ISSUE TITLE
Tinkers_Construct crashing minecraft

### ISSUE THREAD

**Issue by bricky1** [John-Smith-Modded/JSTR-Modded-1.12.x#2]
Please forgive me, as I'm brand new to this website, but I would like to help out and report a crash issue that I'm experiencing with the Tinkers_Construct textures.

Currently, minecraft will not successfully launch and simply crash when attempting to use the Tinkers_Construct textures along with the vanilla textures downloaded from this website. I suspect it may be because I'm using the latest version of the mod (2.9.0.55), when I believe the current textures were uploaded for version 2.7.4.

I absolutely love the work that's being put into these textures: they're brilliant and I hope I can help this to be fixed. 

I will check back on this frequently, if there is any more information I can provide in order to help this issue.

Thank you!

Edit: Would a crash log help? And if so, how would I go about posting / formatting it?

**Comment by ScottKillen** [comment]
Please post a link to the latest-fml-client.log. (I could have the name wrong) _**Very important:**_ **NOT** the crash log!

**Comment by Naddox** [comment]
Since last file didn't have the crash in the log, this time I went in game before activating the texture pack. Crashed as soon as I added it. The log does show crash at the very end now.

https://gist.githubusercontent.com/Naddox/af1dd3aa6770e7a1dfa55c5660addbfa/raw/6cc0c41fe7c0f379ff281c9d8c22bef8a6a6fed4/fml-client-latest.log%252001-22-18

Note you have to view the log in raw text as gist only displays the first ~7000 lines of code but the whole file is 29600 lines.

And even though you said you don't need the crash log, here it is.

https://gist.github.com/Naddox/ac0be09a02a127b2ac39442814d89ccf

**Comment by ScottKillen** [comment]
According to the log, it is crashing because tconstruct:items/cleaver/handle_ardite is missing; however, this texture does not exist in the mod, nor the resource pack.

In other words...we retextured the mod and because we don't have an **extra** texture that is not in the mod itself the game crashes. I suspect that other resource packs will have this same issue, which would be an indication that the issue is with the mod itself, or perhaps changes that forge has made to the texture atlas builder (though that is much less likely).

This is further indicated by the fact that the bug happened when you upgraded the mod--yet I can find no significant difference between the resources included in the latest version of the mod versus earlier versions.

My recommendation is to verify this error with other texture packs that fully support tconstruct and then report this to the mod developer.

**Comment by ScottKillen** [comment]
Also--I just noticed this--the original poster says that TConstruct is crashing with JS _Vanilla_, which would indicate that the latest version of TConstruct just doesn't like resourcepacks, _whether they support TConstruct or not_.

**Comment by bricky1** [comment]
@ScottKillen The crash doesn't occur with just JS Vanilla textures. It only occurs when the TConstruct textures are also added. 

Also, I just tried vanilla+tinkers textures with an earlier version of the mod (2.7.4.43) and it worked fine. Textures all working and no crash. The crash only seems to happen with the latest version (2.9.0.55).

Any ideas?

**Comment by bricky1** [comment]
@ScottKillen The latest version of the mod seems to work fine with another texture pack I have tried: Soartex

**Comment by ScottKillen** [comment]
OK. I'm all out of ideas, but some of the Soartex guys are part of this project, too. (And they know more than me. :smiley:) 
@Shoeboxam @Oddface @goldbattle

**Comment by bricky1** [comment]
@ScottKillen I just looked at the gist provided by another user above, and noticed that their crash might be slightly different. I've uploaded the gist. Please take a look

https://gist.githubusercontent.com/bricky1/fc53aaa137e5820ac728b3d921ad8d53/raw/5e6d69184eb1999604f8421253763c312212fa0c/gistfile1.txt

My apologies for the delay

**Comment by ScottKillen** [comment]
@bricky1 LOL

Your log shows a crash in extrautils2 because he tried to divide by zero. This should definitely be reported to rwtema so he can fix it.

**Comment by bricky1** [comment]
@ScottKillen So there would be no way to fix this via the resource pack? Seems an odd crash

**Comment by ScottKillen** [comment]
RWTema's code is not open source and so it is difficult to debug. It appears to have something to do with TConstruct textures and could even be a part of this other issue... (and I don't even know what that is)

But...I do know that @RWTema is an excellent developer and the fact that an unchecked division by zero error in a compatibility module is causing a crash will drive him nutz The fix should be relatively easy.

If I understood how to fix it in the resource pack I would.

From everything I can see, it looks like some of the advanced rendering code in the latest version of TConstruct makes some assumptions that JohnSmith doesn't meet. Unfortunately these aren't documented...and so I have reported the issue to the TConstruct team in hopes that they will either fix the issue or document their expectations so we can fix the issue.

**Comment by bricky1** [comment]
Okay. Thank you. I'm not sure what to do from here, or how to report things to @rwtema but I hope that I've helped somewhat. 

Thanks again

**Comment by ScottKillen** [comment]
We've tagged him here--so he should get an email. He also keeps an issues link [here](https://minecraft.curseforge.com/projects/extra-utilities) that can be used to report things like this.

**Comment by ScottKillen** [comment]
You might also try posting a comment at that link.

**Comment by artdude543** [comment]
I'll debug this issue; I've encountered it before with an old bug with texture sizing and the mod not handling higher res. Can't remember how the fix was done on Fanver's side, but I'll try to re-create this to look further and suggest a fix if we can on the RP side.

**Comment by artdude543** [comment]
Can I ask what modpack you are using @bricky1 ?

**Comment by bricky1** [comment]
@artdude543 FTB Revelation 1.3.0

**Comment by artdude543** [comment]
Found the bug it's an issue with JSTR I blame @Oddface the model override is out of date to the mod. Which is looking in the wrong directory for a layer. Will push out a commit and one of the guys here will push out a release for the fix :)

**Comment by bricky1** [comment]
@artdude543 You work fast. Impressive. Well done and thanks!

**Comment by artdude543** [comment]
I've been doing this for a while now and know where to look first before major debugging ^_^

**Comment by ScottKillen** [comment]
@bricky1 I told you they knew more than me!

**Comment by Oddface** [comment]
That's what I was thinking. I'm looking at the newest version and I don't see what changed.

**Comment by artdude543** [comment]
From all the debugging I did in regards to the issue the model file was the issue from the start. Testing around with differ mod versions with and w/o the override was causing the crash each time. I could not perform additional testing to find the root cause (but other mainstream RP's don't have the issue at all nor are using overrides).

If anyone has any doubts then please debug this further. But at the time a fix was needed for the user here and for a streamer, I was watching at the time. But the crash was reproducible each time in both Fanver and JSTR when using the model overrides created on this RP.

**Comment by bonii-xx** [comment]
I'm still curious though, from a glance over the model I was under the impression that it should've worked.
