### ISSUE TITLE
Chisel Support

### ISSUE THREAD

**Issue by AshnakAGQ** [John-Smith-Modded/JSTR-Modded-1.12.x#35]
My primary concern is the Auto Chisel GUI. It's pretty much unusable.

If you have time, half the cobblestone textures are missing. I personally don't mind if all the textures are missing, or all the textures are complete, as long as they fit well together. My base is half one color and half another.

![image](https://user-images.githubusercontent.com/23924004/57518915-0c335c00-72cf-11e9-90b3-2862ad64f71d.png)

**Comment by lesdmark** [comment]
I will go ahead and take a look at the autochisel and get it sorted. As far as the cobble and such I know how you feel about it being a mixed bag. Sadly I am mostly working on this by myself atm, and there are so many mods with so many textures.

**Comment by lesdmark** [comment]
Ok the change has been made to the repository. You can either add it yourself if you know how, or wait until I create a new release which could be a bit. Have a good one.

**Comment by ScottKillen** [comment]
I'm currently working on these textures.

**Comment by lesdmark** [comment]
Fantastic! I'm glad someone is. It's a lot to take on. I tend to not use chisel blocks very much specifically because there are so many that are un-retextured.

**Comment by ScottKillen** [comment]
Yes.

It has bugged me since Chisel became a thing. I have begun this several times...but this time will be the one.

@AshnakAGQ This might take a while because of the quantity of different types of blocks and the quantity of materials. I am building Photoshop templates for each block. That will take a bit...but then I can add a full set of blocks for each material relatively quickly.

**Comment by AshnakAGQ** [comment]
Thanks!
