### ISSUE TITLE
[request] AE2 Wireless Transmitter

### ISSUE THREAD

**Issue by netish** [John-Smith-Modded/JSTR-Modded-1.12.x#51]
Hey love the work that's been done with this texture pack. I was wondering if this small mod could be done - and/or if someone could suggest a little about how to do it myself? It currently seems to be causing me a [crash](https://pastebin.com/YmUHwv0y) in the creative menu?

**Comment by ScottKillen** [comment]
Hey!

I took a look at the logs you provided.

This may be caused by the resource pack--but it shouldn't be. The resource pack just provides alternate graphics and if it doesn't provide them, the default behavior should be to fall through and use the textures provided by the mod.

Whether an update is done here or not, you need to let @p455w0rd know this is happening by reporting the crash over at https://github.com/p455w0rd/AE2WirelessTerminalLibrary/issues/new and providing all of the details. He is a great dev so, at a very minimum, he will want to know about this so his  code can anticipate this crash and avoid it.

**Comment by netish** [comment]
I just didn't get the crash until I used the texture pack...which makes me think it is related...

**Comment by ScottKillen** [comment]
It probably is, but the mod shouldn't react like that to a texture problem...

**Comment by netish** [comment]
Hmm, I tried another resource pack and the same things happened...it seems to be related to how the creative menu gui interacts with the mod when edited by ANY resource pack. Closing this and moving it to the mod's page. (Thanks for the link earlier.)
