### ISSUE TITLE
[Request] Specific Suggestions

### ISSUE THREAD

**Issue by netish** [John-Smith-Modded/JSTR-Modded-1.12.x#52]
So, love this pack but ran into one deal breaker for me - the villagers look downright disturbing!!! I don't know if this is just my opinion but...too creepy for me!

On a side note - there are some natura and bop leaves that have their textures changed but they now have too much white and look awful. I can specifically name the wasteland trees from bop off the top of my head.

**Comment by ScottKillen** [comment]
FWIW,

Tastes vary. I love this pack, but there are some things about it that also don't sit right with me....

...which is why I have ANOTHER private custom pack installed above this, that contains my custom edits. If you find villagers that you like, or better leaves, etc., you can put them in the custom pack and they will override the textures in the same path in the pack lower in the list.

The custom pack can be an uncompressed folder, rather than a zip file and you can add textures to it while in game, then press `F3` + `T` to refresh your textures.

By doing this, I get to enjoy the mastery that is JohnSmith, while tweaking my personal annoyances.

I'm closing this issue...because, in fairness, "Make villagers less disturbing and creepy for me!" isn't really an actionable suggestion. :wink:

**Comment by netish** [comment]
I see your point - which is why I offered this as a suggestion - also talking about the leaves with problems. However, I will look into making a custom pack - thanks for the info!
